
name: Build master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    env:
      OPAMROOT: /home/user/.opam

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:pltlab
      options: --user user

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - run: opam update
      - run: opam --version
      - run: opam exec -- ocamlopt --version


      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - run: |
          sudo apt-get update
          sudo apt-get install racket racket-doc libssl-dev openjdk-17-jdk -y --no-install-recommends
      # https://github.com/racket/racket/issues/4306
      # libssl-dev might be mandatory
      # https://github.com/racket/racket/issues/2691#issuecomment-812963346
      - name: Install Racket dependencies
        run: |
          sudo chown `whoami` -R /usr/share/racket/collects/
          sudo chown `whoami` -R /usr/share/racket/pkgs
          sudo chown `whoami` -R /usr/share/doc/racket
          raco setup --doc-index --force-user-docs
          raco pkg install --skip-installed --user benchmark pretty-format

      - run: opam install OCanren OCanren-ppx --yes --deps-only --with-test #--with-doc

      - run: opam exec -- dune test # dune runtest
