
name: Build master

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'

env:
  OPAMROOT: /home/user/.opam
  OPAMYES: true

jobs:
  build:
    env:
      OPAMROOT: /home/user/.opam

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:minikanren2023
      options: --user user

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - run: opam update
      - run: opam --version
      - run: opam exec -- ocamlopt --version
      - run: opam list

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - if: false
        run: |
          sudo apt-get update
          sudo apt-get install racket racket-doc libssl-dev openjdk-17-jdk -y --no-install-recommends
      # https://github.com/racket/racket/issues/4306
      # libssl-dev might be mandatory
      # https://github.com/racket/racket/issues/2691#issuecomment-812963346

      - name: Install Racket dependencies
        run: |
          raco pkg install --skip-installed --user benchmark pretty-format

      - run: raco pkg show

      - if: false
        run: opam install OCanren OCanren-ppx --yes --deps-only --with-test #--with-doc

      - run: opam exec -- make test build_benches
